name: Build and Release

on:
  push:
    tags:
    - 'v*' # Trigger für Tags, die mit 'v' beginnen

permissions:
  contents: write

jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Create Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automatisch erstellte Release für Tag ${{ github.ref }}
        draft: false
        prerelease: false

    # Zip specific files or folders
    - name: Create ZIP Archive
      run: |
        zip -r release.zip strt --exclude *.txt

    # Upload ZIP to Release
    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release.zip
        asset_name: release.zip
        asset_content_type: application/zip